WD = '/Users/djohnson/compile/DSSGxUK-ITU/'
#COUNTRY = 'Philippines'
#COUNTRY_CODE = 'phl'
COUNTRY = 'Armenia'
COUNTRY_CODE = 'arm'
AVAILABLE_COUNTRIES = ['bra', 'tha', 'phl'] # list of country names  
#FEATURES = ['satellite', 'facebook', 'opencell', 'population', 'speedtest']  # one or multiple of'population', 'facebook', 'opencell', 'satellite', 'speedtest'
FEATURES = ['speedtest']  # one or multiple of'population', 'facebook', 'opencell', 'satellite', 'speedtest'
SCHOOL_BUFFER = 1  # in kilometers
SURVEY_AREAS = ''
SATELITTE_COLLECTIONS = {'CSP/HM/GlobalHumanModification': None, 'NOAA/VIIRS/DNB/MONTHLY_V1/VCMSLCFG': ['avg_rad', 'cf_cvg'], 'MODIS/006/MOD13A2': ['NDVI']}
SATELITTE_START_YEAR = 2014 # should be at least 2014
SATELITTE_END_YEAR = 2019 # 2021 might be exist for some collections..
SATELITTE_BUFFER = 5 # in kilometers
SATELITTE_MAX_CALL_SIZE = 5000 # default max call size
SATELITTE_IMAGE_SCALE = 30
GOOGLE_SERVICES_ACCOUNT = 'itu-access@itu-country-data-collection.iam.gserviceaccount.com'
GOOGLE_EARTH_ENGINE_API_JSON_KEY = 'itu-country-data-collection-ed2c27ca083e.json'
OPENCELLID_ACCESS_TOKEN = '1fa55d488350b1' # 2 calls per day
FACEBOOK_MARKETING_API_ACCESS_TOKEN = 'EAAOoScy84B8BAFvjycJuAkWQG3AF6QZBRtnZAF3Aqe1HihEX6XFUJGyVkg72FdkEZCclX5mpNRki6nocvLpA3Avox2BxdadlZArDLXeKDCmSQOGzVLvaM1paxpEyAD7L6wWlZCmREpxVqLtKwdQUwjteZBcB6xKxxl8K1pAn5VpPsC1R1S6kWE'
FACEBOOK_AD_ACCOUNT_ID = 'act_87134545'
FACEBOOK_CALL_LIMIT = 300 # default fb ad_services call size
FACEBOOK_RADIUS = 5 # in kilometers
#FACEBOOK_SCHOOL_DATA_LEN = {'bra': 11732, 'tha': 4723, 'phl': 4599 }
FACEBOOK_SCHOOL_DATA_LEN = {'arm': 1087}
SPEEDTEST_TILE_TYPE = 'fixed' # can be 'fixed' or 'mobile'
SPEEDTEST_TILE_YEAR = 2021 # data is available quarterly and usually approximately 1 month after quarter ends 
SPEEDTEST_TILE_QUARTER = 2 # 1-4 integer
POPULATION_DATASET_YEAR = 2020 # dataset currently available for years 2000-2020
